development:
  clients:
    default:
      database: simple-note
      hosts:
        - cluster0-shard-00-00.kbxnd.mongodb.net:27017
        - cluster0-shard-00-01.kbxnd.mongodb.net:27017
        - cluster0-shard-00-02.kbxnd.mongodb.net:27017
      options:
        user: <%= ENV["DB_APP_NAME"] %>
        password: <%= ENV["DB_ACCESS_KEY"] %>
        ssl: true
        server_selection_timeout: 5
        auth_source: admin
  options:
test:
  clients:
    default:
      database: simple-note
      hosts:
        - cluster0-shard-00-00.kbxnd.mongodb.net:27017
        - cluster0-shard-00-01.kbxnd.mongodb.net:27017
        - cluster0-shard-00-02.kbxnd.mongodb.net:27017
      options:
        read:
          mode: :primary
        user: <%= ENV["DB_APP_NAME"] %>
        password: <%= ENV["DB_ACCESS_KEY"] %>
        max_pool_size: 1
        server_selection_timeout: 5
        ssl: true
        auth_source: admin
